name: Update gist with latest Bilibili videos
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "25 8 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Deno"
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: e8ff9fc13066c6f8eed3ad28ae9e7638
          UID: '23736703'
        run: deno run --allow-net --allow-env index.ts
